// Code generated by protoc-gen-go.
// source: chat_service.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	chat_service.proto

It has these top-level messages:
	WebMessage
	GetMessageRequest
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type WebMessage struct {
	Text string `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
}

func (m *WebMessage) Reset()                    { *m = WebMessage{} }
func (m *WebMessage) String() string            { return proto1.CompactTextString(m) }
func (*WebMessage) ProtoMessage()               {}
func (*WebMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *WebMessage) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type GetMessageRequest struct {
	Text string `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
}

func (m *GetMessageRequest) Reset()                    { *m = GetMessageRequest{} }
func (m *GetMessageRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetMessageRequest) ProtoMessage()               {}
func (*GetMessageRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetMessageRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func init() {
	proto1.RegisterType((*WebMessage)(nil), "proto.WebMessage")
	proto1.RegisterType((*GetMessageRequest)(nil), "proto.GetMessageRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Chat service

type ChatClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (Chat_ConnectClient, error)
	GetMessage(ctx context.Context, in *GetMessageRequest, opts ...grpc.CallOption) (*WebMessage, error)
}

type chatClient struct {
	cc *grpc.ClientConn
}

func NewChatClient(cc *grpc.ClientConn) ChatClient {
	return &chatClient{cc}
}

func (c *chatClient) Connect(ctx context.Context, opts ...grpc.CallOption) (Chat_ConnectClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Chat_serviceDesc.Streams[0], c.cc, "/proto.Chat/connect", opts...)
	if err != nil {
		return nil, err
	}
	x := &chatConnectClient{stream}
	return x, nil
}

type Chat_ConnectClient interface {
	Send(*WebMessage) error
	Recv() (*WebMessage, error)
	grpc.ClientStream
}

type chatConnectClient struct {
	grpc.ClientStream
}

func (x *chatConnectClient) Send(m *WebMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *chatConnectClient) Recv() (*WebMessage, error) {
	m := new(WebMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *chatClient) GetMessage(ctx context.Context, in *GetMessageRequest, opts ...grpc.CallOption) (*WebMessage, error) {
	out := new(WebMessage)
	err := grpc.Invoke(ctx, "/proto.Chat/GetMessage", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Chat service

type ChatServer interface {
	Connect(Chat_ConnectServer) error
	GetMessage(context.Context, *GetMessageRequest) (*WebMessage, error)
}

func RegisterChatServer(s *grpc.Server, srv ChatServer) {
	s.RegisterService(&_Chat_serviceDesc, srv)
}

func _Chat_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChatServer).Connect(&chatConnectServer{stream})
}

type Chat_ConnectServer interface {
	Send(*WebMessage) error
	Recv() (*WebMessage, error)
	grpc.ServerStream
}

type chatConnectServer struct {
	grpc.ServerStream
}

func (x *chatConnectServer) Send(m *WebMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *chatConnectServer) Recv() (*WebMessage, error) {
	m := new(WebMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Chat_GetMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).GetMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Chat/GetMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).GetMessage(ctx, req.(*GetMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Chat_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Chat",
	HandlerType: (*ChatServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMessage",
			Handler:    _Chat_GetMessage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "connect",
			Handler:       _Chat_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "chat_service.proto",
}

func init() { proto1.RegisterFile("chat_service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 152 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4a, 0xce, 0x48, 0x2c,
	0x89, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62,
	0x05, 0x53, 0x4a, 0x0a, 0x5c, 0x5c, 0xe1, 0xa9, 0x49, 0xbe, 0xa9, 0xc5, 0xc5, 0x89, 0xe9, 0xa9,
	0x42, 0x42, 0x5c, 0x2c, 0x25, 0xa9, 0x15, 0x25, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60,
	0xb6, 0x92, 0x3a, 0x97, 0xa0, 0x7b, 0x6a, 0x09, 0x54, 0x45, 0x50, 0x6a, 0x61, 0x69, 0x6a, 0x71,
	0x09, 0x36, 0x85, 0x46, 0x55, 0x5c, 0x2c, 0xce, 0x19, 0x89, 0x25, 0x42, 0xa6, 0x5c, 0xec, 0xc9,
	0xf9, 0x79, 0x79, 0xa9, 0xc9, 0x25, 0x42, 0x82, 0x10, 0xcb, 0xf4, 0x10, 0x56, 0x48, 0x61, 0x0a,
	0x29, 0x31, 0x68, 0x30, 0x1a, 0x30, 0x0a, 0x59, 0x73, 0x71, 0x21, 0xec, 0x11, 0x92, 0x80, 0x2a,
	0xc3, 0xb0, 0x1a, 0xab, 0x01, 0x49, 0x6c, 0x60, 0x31, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x90, 0x53, 0xd7, 0xf5, 0xea, 0x00, 0x00, 0x00,
}
